celery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("contact_form.urls")),
    path("server_demo/", include("stream_m3u8.urls"))
]

stream_m3u8/urls.py
from django.urls import path

from .views import StartStreamView, StopStreamView

app_name = "stream_m3u8"
urlpatterns = [
    path("", StartStreamView.as_view(), name="start_stream"),
    path("stop/", StopStreamView.as_view(), name="stop_stream")
]

stream_m3u8/models.py
from django.db import models

# Create your models here.

stream_m3u8/views.py
from django.shortcuts import render, redirect
from django.views import View
from .tasks import stream_task, test_task
# Create your views here.
is_live = False
url_list = []
task = None

class StartStreamView(View):
    def get(self, request):
        global is_live
        if task is None:
            is_live = False
        elif task.state == "PROGRESS" or task.state == "STARTED":
            is_live = True
        else:
            is_live = False
        if task is not None:
            print(task.state)
        context = {
            "is_live": is_live,
            "url_list": url_list
        }
        return render(request, "stream_m3u8/start_stream.html", context)

    def post(self, request):
        global url_list, task_id, task
        print(request.POST)
        url_list = [
            request.POST.get("url1", ""),
            request.POST.get("url2", ""),
            request.POST.get("url3", "")
        ]
        task = stream_task.delay(url_list)
        print(task.id)
        return redirect('stream_m3u8:start_stream')


class StopStreamView(View):
    def post(self, request):
        global task
        task.revoke(terminate=True)
        return redirect('stream_m3u8:start_stream')
    # def post(self, request):

stream_m3u8/templates/stream_m3u8/start_stream.html
{% load static %}
<html>
<head>
    <title> Demo Stream Admin</title>
    <link href="{% static 'bootstrap-4.0.0-beta-dist/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
</head>
<body>
<div class="container">
<h3 style="margin-top: 30px;margin-bottom: 30px">
    Admin Demo Stream (<a href="@:8088/hls/stream/index.m3u8">/hls/stream/index.m3u8</a>)
</h3>
{% if is_live %}

    <form method="post" action="{% url 'stream_m3u8:stop_stream' %}">
    {% csrf_token %}
        <ul>
            {% for url in url_list %}
                <li>{{ url }}</li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-primary">Stop</button>
    </form>

{% else %}
    <form method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="url1">URL 1</label>
            <input name="url1" type="text" class="form-control" id="url1"
                   placeholder="Input the stream url">
            <small id="emailHelp" class="form-text text-muted">We'll concat the stream content into single stream</small>
        </div>
        <div class="form-group">
            <label for="url2">URL 2</label>
            <input name="url2" type="text" class="form-control" id="url2"
                   placeholder="Input the stream url">
        </div>
        <div class="form-check">
            <label for="url3">URL 3</label>
            <input name="url3" type="text" class="form-control" id="url3"
                   placeholder="Input the stream url">
        </div>
        <button type="submit" class="btn btn-primary">Start</button>
    </form>
{% endif %}
</div>
</body>
<script src="{% static 'vendors/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap-4.0.0-beta-dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/jquery.toast.min.js' %}"></script>
</html>